/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portal.model;

import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PasswordPolicyRel service. Represents a row in the &quot;PasswordPolicyRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.PasswordPolicyRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.PasswordPolicyRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PasswordPolicyRel
 * @see com.liferay.portal.model.impl.PasswordPolicyRelImpl
 * @see com.liferay.portal.model.impl.PasswordPolicyRelModelImpl
 * @generated
 */
public interface PasswordPolicyRelModel extends BaseModel<PasswordPolicyRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a password policy rel model instance should use the {@link PasswordPolicyRel} interface instead.
	 */

	/**
	 * Gets the primary key of this password policy rel.
	 *
	 * @return the primary key of this password policy rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this password policy rel
	 *
	 * @param pk the primary key of this password policy rel
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the password policy rel id of this password policy rel.
	 *
	 * @return the password policy rel id of this password policy rel
	 */
	public long getPasswordPolicyRelId();

	/**
	 * Sets the password policy rel id of this password policy rel.
	 *
	 * @param passwordPolicyRelId the password policy rel id of this password policy rel
	 */
	public void setPasswordPolicyRelId(long passwordPolicyRelId);

	/**
	 * Gets the password policy id of this password policy rel.
	 *
	 * @return the password policy id of this password policy rel
	 */
	public long getPasswordPolicyId();

	/**
	 * Sets the password policy id of this password policy rel.
	 *
	 * @param passwordPolicyId the password policy id of this password policy rel
	 */
	public void setPasswordPolicyId(long passwordPolicyId);

	/**
	 * Gets the class name of the model instance this password policy rel is polymorphically associated with.
	 *
	 * @return the class name of the model instance this password policy rel is polymorphically associated with
	 */
	public String getClassName();

	/**
	 * Gets the class name id of this password policy rel.
	 *
	 * @return the class name id of this password policy rel
	 */
	public long getClassNameId();

	/**
	 * Sets the class name id of this password policy rel.
	 *
	 * @param classNameId the class name id of this password policy rel
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Gets the class p k of this password policy rel.
	 *
	 * @return the class p k of this password policy rel
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this password policy rel.
	 *
	 * @param classPK the class p k of this password policy rel
	 */
	public void setClassPK(long classPK);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PasswordPolicyRel passwordPolicyRel);

	public int hashCode();

	public PasswordPolicyRel toEscapedModel();

	public String toString();

	public String toXmlString();
}